server:
  port: 9090
  servlet:
    context-path: /hi/
  ssl:
    key-store: classpath:jiaohongtao.com.pfx
    key-store-password: 5t0krowrx56
    key-store-type: PKCS12
    enabled: true

spring:
  thymeleaf:
    enabled: true  #开启thymeleaf视图解析
    encoding: utf-8  #编码
    # prefix: classpath:/templates/  #前缀
    cache: false  #是否使用缓存
    # mode: HTML  #严格的HTML语法模式
    suffix: .html  #后缀名
  mvc:
    static-path-pattern: /**
  devtools:
    # 开启热部署
    restart:
      enabled: true
      # 监听目录
      additional-paths: src/main/java

  # redis配置
  redis:
    # Redis数据库索引（默认为0）
    database: 0
    # Redis服务器地址
    host: 127.0.0.1
    # Redis服务器连接端口
    port: 6379
    # Redis服务器连接密码（默认为空）
    password: 123456
    # 连接超时时间（毫秒）
    timeout: 1000
    lettuce:
      pool:
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 200
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1
        # 连接池中的最大空闲连接
        max-idle: 10
        # 连接池中的最小空闲连接
        min-idle: 0

  # 漂亮打印Spring Boot Actuator端点的JSON输出, 不只是 actuator 使用
  jackson:
    serialization:
      indent_output: true
my:
  name: jiaohongtao

# actuator
management:
  server:
    # actuator 的访问端口
    port: 8081
    ssl:
      key-store: classpath:jiaohongtao.com.pfx
      key-store-password: 5t0krowrx56
      key-store-type: PKCS12
      enabled: true
  endpoints:
    web:
      # 根路径 端口后的路径，无需要添加项目的初始路径
      base-path: /actuator/base
      exposure:
        include: '*'
